### Exercise 2

**#1.**

The null hypothesis is that there is no strong relationship between TV, radio and newspaper and sales.

TV and radio have strong relationship with sales, but newspaper does not. The intercept represents the baseline of sales, and it is 2,939 units. It is estimated that 46 units will be added to the sales with $1,000 spent on TV.

**#2.**

The KNN regression method is closely related to the KNN classifier.

KNN classifier takes a single observation as an input and yields an output. While KNN regression estimates f(x), it becomes a function.

**#3.**

**(a)**
Y = 50 + 20(GPA) + 0.07(IQ) + 35(Gender) + 0.01(GPA * IQ) - 10(GPA * Gender)

Female: Y =  50 + 20(GPA) + 0.07(IQ) + 35 + 0.01(GPA * IQ) - 10(GPA)

Male: Y = 50 + 20(GPA) + 0.07(IQ) + 0.01(GPA * IQ)

Male is the baseline. Female has the 35. Therefore if GPA is high enough(more than 3.5), then males earn more.

**(b)**
Y(Female) = 50 + 80 + 7.7 + 35 + 4.4 - 40 

**(c)**
False. The impact of interaction term does not depend on the coefficient, but the P value instead. 


**#4.**

**(a)**
Training RSS for the cubic regression should be lower, since it is more flexible and fits the data better (actually overfitting).

**(b)**
Test RSS is higher, since it is overfitting. The model tends to fit the noise and have less accuracy on underlying distribution.

**(c)**
Training RSS for the cubic is lower.

**(d)**
It depends on how far the true relationship is from the linear regression. If it is close to the linear, then the test RSS for cubic is lower. Otherwise, the test RSS is higher.

**#5.**





